export { OpenRouterClient, OpenRouterApiError, OpenRouterConfigError } from "./client";
export { DEFAULT_BASE_URL, normalizeBaseUrl, isCustomEndpointUrl } from "./base-url";
export {
  getOpenRouterSettings,
  getTranslationSettings,
  getOpenRouterClient,
  updateSetting,
  updateSettings,
  maskApiKey,
  isCustomEndpoint,
  getEffectiveModel,
} from "./settings";
export {
  SETTINGS_KEYS,
  POPULAR_MODELS,
  POPULAR_EMBEDDING_MODELS,
  DEFAULT_EMBEDDING_MODEL,
  DEFAULT_EMBEDDING_DIMENSIONS,
  DEFAULT_EMBEDDING_IMAGE_MAX_RESOLUTION,
  EMBEDDING_DIMENSION_OPTIONS,
  EMBEDDING_RESOLUTION_OPTIONS,
  modelSupportsVision,
  type ModelDefinition,
  type OpenRouterClientConfig,
  type OpenRouterSettings,
  type ChatMessage,
  type ChatCompletionRequest,
  type ChatCompletionResponse,
  type TranslationRequest,
  type TranslationResult,
  type ImageTranslationRequest,
  type ImageTranslationResult,
  type EmbeddingRequest,
  type EmbeddingResponse,
  type EmbeddingResult,
  type ImageEmbeddingRequest,
  type ImageEmbeddingsRequest,
} from "./types";
export {
  estimateTokens,
  estimateTranslationCost,
  getModelPricing,
  warmPricingCache,
  formatCost,
  type ModelPricing,
  type CostEstimate,
} from "./pricing";
